# Generated by Django 3.1.3 on 2020-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailid',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='email_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
