# Generated by Django 3.1.3 on 2020-11-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0002_auto_20201106_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
