# Generated by Django 3.1.3 on 2020-11-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0003_auto_20201110_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'not accepted'), ('delivered', 'on process')], max_length=20, null=True)),
                ('delivery_address', models.CharField(max_length=100, null=True)),
                ('total_bill', models.IntegerField(null=True)),
                ('order_num', models.IntegerField(unique=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnapp.customer')),
            ],
        ),
    ]
