# Generated by Django 3.1.3 on 2020-11-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0005_category_ordered_item_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('not accepted', 'not accepted'), ('delivered', 'delivered'), ('on process', 'on process')], max_length=20, null=True),
        ),
    ]
