# Generated by Django 3.1.3 on 2020-11-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0006_auto_20201111_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnapp.customer')),
                ('product_id', models.ManyToManyField(to='furnapp.product')),
            ],
        ),
    ]
