# Generated by Django 3.1.3 on 2020-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='static/img/gallery'),
        ),
    ]
